name: CI/CD Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest httpx

      - name: Ejecutar pruebas
        run: pytest

      # Despliegue a Azure Web App (descomenta y configura si lo necesitas)
      # - name: 'Desplegar a Azure Web App'
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: '<NombreDeTuAppService>'
      #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
      #     package: '.'